security:
    encoders:
        App\Entity\Person:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2a$08$jHZj/wJfcVKlIwr5AvR78euJxYK7Ku5kURNhNx.7.CSIJ3Pq6LEPC
                        roles: 'Admin'
        db_person_provider:
            entity:
                class: App\Entity\Person
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: db_person_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: home
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/users, roles: Admin }
        # - { path: ^/profile, roles: ROLE_USER }
