index:
    path: /
    controller: App\Controller\DefaultController::index

logout:
    path: /logout
    
controllers:
    resource: ../src/Controller/
    type: annotation
    
login:
    path: /login
    controller: App\Controller\SecurityController::login